import type { Investment, PurchaseOrder } from "@prisma/client";
import type { InvestmentFund } from "@/lib/config/investmentFunds";
import { APP_NAME } from "@/lib/constants/appBranding";
import { insightsFromInvestment } from "@/services/wallets/transactionInsights";

export type ReceiptDocumentLine = {
  label: string;
  value: string;
};

export type ReceiptDocumentSection = {
  title: string;
  lines: ReceiptDocumentLine[];
};

export type ReceiptDocument = {
  brand: string;
  heading: string;
  amount: string;
  description: string;
  footer: string;
  sections: ReceiptDocumentSection[];
};

function formatUsdtNumber(value: number): string {
  return value.toFixed(2);
}

function formatReceiptDate(value: Date | null | undefined): string {
  if (!value) {
    return "—";
  }
  return value.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

export function buildInvestmentReceiptDocument(params: {
  investment: Investment;
  order: PurchaseOrder;
  fund: InvestmentFund;
  appName?: string;
}): ReceiptDocument {
  const { investment, order, fund } = params;
  const appName = params.appName ?? APP_NAME;
  const insights = insightsFromInvestment(investment, fund);
  const txId = order.usdtTxId ?? "";
  const subscribedAt = investment.subscribedAt ?? investment.date;

  const transactionLines: ReceiptDocumentLine[] = [
    { label: "Status", value: "Active" },
    { label: "Date", value: formatReceiptDate(subscribedAt) },
    { label: "Fund", value: fund.name },
    { label: "Amount", value: `${formatUsdtNumber(investment.amountUsdt)} USDT` },
  ];

  if (txId) {
    transactionLines.push({ label: "Transaction ID", value: txId });
  }

  transactionLines.push({ label: "Investment ID", value: investment.id });

  const investmentLines: ReceiptDocumentLine[] = [
    {
      label: "Principal",
      value: `${formatUsdtNumber(insights.principalUsdt)} USDT`,
    },
    {
      label: "Target return",
      value: `${insights.targetReturnPercent}%`,
    },
    {
      label: "Projected payout",
      value: `${formatUsdtNumber(insights.projectedPayoutUsdt)} USDT`,
    },
    {
      label: "Expected earnings",
      value: `${formatUsdtNumber(insights.expectedEarningsUsdt)} USDT`,
    },
    {
      label: "Invested on",
      value: formatReceiptDate(subscribedAt),
    },
    {
      label: "Maximum term date",
      value: formatReceiptDate(investment.maturesAt),
    },
  ];

  return {
    brand: appName,
    heading: "Transaction receipt",
    amount: `-${formatUsdtNumber(investment.amountUsdt)} USDT`,
    description: `Investment (${fund.name})`,
    footer: `This document was generated by ${appName} for your records.`,
    sections: [
      { title: "Transaction", lines: transactionLines },
      { title: "Investment details", lines: investmentLines },
    ],
  };
}

export function investmentReceiptFilename(txId: string | null | undefined): string {
  const shortId = (txId ?? "investment").slice(0, 12);
  return `indiefundr-receipt-${shortId}.pdf`;
}
