import type { Investment, ReferralPayoutOrder, WithdrawalOrder } from "@prisma/client";
import { ReferralPayoutOrderKind } from "@prisma/client";
import type { InvestmentFund } from "@/lib/config/investmentFunds";
import { APP_NAME } from "@/lib/constants/appBranding";
import { insightsFromRedemption } from "@/services/wallets/transactionInsights";
import type {
  ReceiptDocument,
  ReceiptDocumentLine,
} from "./investmentReceiptDocument";

export type UserPaymentKind =
  | "investment_payout"
  | "referral_invitee_bonus"
  | "referral_inviter_bonus"
  | "principal_recovery"
  | "withdrawal";

export function referralOrderKindToUserPaymentKind(
  kind: ReferralPayoutOrderKind
): Exclude<UserPaymentKind, "investment_payout" | "withdrawal"> {
  switch (kind) {
    case ReferralPayoutOrderKind.invitee_bonus:
      return "referral_invitee_bonus";
    case ReferralPayoutOrderKind.inviter_bonus:
      return "referral_inviter_bonus";
    case ReferralPayoutOrderKind.principal_recovery:
      return "principal_recovery";
  }
}

export function userPaymentKindLabel(kind: UserPaymentKind): string {
  switch (kind) {
    case "investment_payout":
      return "Investment payout";
    case "referral_invitee_bonus":
      return "Referral welcome bonus";
    case "referral_inviter_bonus":
      return "Referral reward";
    case "principal_recovery":
      return "Principal recovery";
    case "withdrawal":
      return "Wallet withdrawal";
  }
}

function formatUsdtNumber(value: number): string {
  return value.toFixed(2);
}

function formatReceiptDate(value: Date | null | undefined): string {
  if (!value) {
    return "—";
  }
  return value.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function baseReceipt(params: {
  appName: string;
  heading: string;
  amount: string;
  description: string;
  transactionLines: ReceiptDocumentLine[];
  detailLines: ReceiptDocumentLine[];
  detailSectionTitle?: string;
}): ReceiptDocument {
  return {
    brand: params.appName,
    heading: params.heading,
    amount: params.amount,
    description: params.description,
    footer: `This document was generated by ${params.appName} for your records.`,
    sections: [
      { title: "Transaction", lines: params.transactionLines },
      {
        title: params.detailSectionTitle ?? "Payment details",
        lines: params.detailLines,
      },
    ],
  };
}

export function buildInvestmentPayoutReceiptDocument(params: {
  investment: Investment;
  fund: InvestmentFund;
  txId: string;
  appName?: string;
}): ReceiptDocument {
  const { investment, fund, txId } = params;
  const appName = params.appName ?? APP_NAME;
  const insights = insightsFromRedemption(investment, fund);
  const credited = insights.creditedUsdt ?? investment.projectedPayoutUsdt;
  const subscribedAt = investment.subscribedAt ?? investment.date;

  const transactionLines: ReceiptDocumentLine[] = [
    { label: "Status", value: "Paid" },
    { label: "Paid on", value: formatReceiptDate(investment.redeemedAt) },
    { label: "Fund", value: fund.name },
    { label: "Amount", value: `${formatUsdtNumber(credited)} USDT` },
    { label: "Transaction ID", value: txId },
    { label: "Investment ID", value: investment.id },
  ];

  const detailLines: ReceiptDocumentLine[] = [
    {
      label: "Principal",
      value: `${formatUsdtNumber(insights.principalUsdt)} USDT`,
    },
    {
      label: "Earnings",
      value: `${formatUsdtNumber(insights.expectedEarningsUsdt)} USDT`,
    },
    {
      label: "Total credited",
      value: `${formatUsdtNumber(credited)} USDT`,
    },
    {
      label: "Invested on",
      value: formatReceiptDate(subscribedAt),
    },
    {
      label: "Maximum term date",
      value: formatReceiptDate(investment.maturesAt),
    },
  ];

  if (insights.payoutDaysElapsed != null) {
    detailLines.push({
      label: "Days invested",
      value: String(insights.payoutDaysElapsed),
    });
  }

  return baseReceipt({
    appName,
    heading: "Payout receipt",
    amount: `+${formatUsdtNumber(credited)} USDT`,
    description: `Payout (${fund.name})`,
    transactionLines,
    detailLines,
    detailSectionTitle: "Payout details",
  });
}

export function buildReferralPayoutReceiptDocument(params: {
  kind: Exclude<UserPaymentKind, "investment_payout" | "withdrawal">;
  order: Pick<
    ReferralPayoutOrder,
    "id" | "amountUsdt" | "date" | "investmentId" | "referralInviteId"
  >;
  txId: string;
  paidAt?: Date;
  appName?: string;
}): ReceiptDocument {
  const { kind, order, txId } = params;
  const appName = params.appName ?? APP_NAME;
  const paidAt = params.paidAt ?? new Date();
  const label = userPaymentKindLabel(kind);

  const transactionLines: ReceiptDocumentLine[] = [
    { label: "Status", value: "Paid" },
    { label: "Paid on", value: formatReceiptDate(paidAt) },
    { label: "Amount", value: `${formatUsdtNumber(order.amountUsdt)} USDT` },
    { label: "Transaction ID", value: txId },
    { label: "Order ID", value: order.id },
  ];

  const detailLines: ReceiptDocumentLine[] = [
    { label: "Payment type", value: label },
    { label: "Amount credited", value: `${formatUsdtNumber(order.amountUsdt)} USDT` },
    { label: "Order created", value: formatReceiptDate(order.date) },
  ];

  if (order.investmentId) {
    detailLines.push({ label: "Investment ID", value: order.investmentId });
  }
  if (order.referralInviteId) {
    detailLines.push({ label: "Referral ID", value: order.referralInviteId });
  }

  return baseReceipt({
    appName,
    heading: "Payout receipt",
    amount: `+${formatUsdtNumber(order.amountUsdt)} USDT`,
    description: label,
    transactionLines,
    detailLines,
  });
}

export function buildWithdrawalReceiptDocument(params: {
  order: Pick<
    WithdrawalOrder,
    "id" | "amountUsdt" | "date" | "destinationAddress"
  >;
  txId: string;
  paidAt?: Date;
  appName?: string;
}): ReceiptDocument {
  const { order, txId } = params;
  const appName = params.appName ?? APP_NAME;
  const paidAt = params.paidAt ?? new Date();
  const label = userPaymentKindLabel("withdrawal");

  const transactionLines: ReceiptDocumentLine[] = [
    { label: "Status", value: "Paid" },
    { label: "Paid on", value: formatReceiptDate(paidAt) },
    { label: "Amount", value: `${formatUsdtNumber(order.amountUsdt)} USDT` },
    { label: "Transaction ID", value: txId },
    { label: "Order ID", value: order.id },
  ];

  const detailLines: ReceiptDocumentLine[] = [
    { label: "Payment type", value: label },
    {
      label: "Amount sent",
      value: `${formatUsdtNumber(order.amountUsdt)} USDT`,
    },
    { label: "Destination", value: order.destinationAddress },
    { label: "Order created", value: formatReceiptDate(order.date) },
  ];

  return baseReceipt({
    appName,
    heading: "Withdrawal receipt",
    amount: `-${formatUsdtNumber(order.amountUsdt)} USDT`,
    description: label,
    transactionLines,
    detailLines,
  });
}

export type BuildUserPaymentReceiptDocumentParams =
  | {
      kind: "investment_payout";
      investment: Investment;
      fund: InvestmentFund;
      txId: string;
    }
  | {
      kind: Exclude<UserPaymentKind, "investment_payout" | "withdrawal">;
      order: Pick<
        ReferralPayoutOrder,
        "id" | "amountUsdt" | "date" | "investmentId" | "referralInviteId"
      >;
      txId: string;
      paidAt?: Date;
    }
  | {
      kind: "withdrawal";
      order: Pick<
        WithdrawalOrder,
        "id" | "amountUsdt" | "date" | "destinationAddress"
      >;
      txId: string;
      paidAt?: Date;
    };

export function buildUserPaymentReceiptDocument(
  params: BuildUserPaymentReceiptDocumentParams & { appName?: string }
): ReceiptDocument {
  switch (params.kind) {
    case "investment_payout":
      return buildInvestmentPayoutReceiptDocument({
        investment: params.investment,
        fund: params.fund,
        txId: params.txId,
        appName: params.appName,
      });
    case "withdrawal":
      return buildWithdrawalReceiptDocument({
        order: params.order,
        txId: params.txId,
        paidAt: params.paidAt,
        appName: params.appName,
      });
    default:
      return buildReferralPayoutReceiptDocument({
        kind: params.kind,
        order: params.order,
        txId: params.txId,
        paidAt: params.paidAt,
        appName: params.appName,
      });
  }
}

export function userPaymentReceiptFilename(txId: string | null | undefined): string {
  const shortId = (txId ?? "payout").slice(0, 12);
  return `indiefundr-payout-${shortId}.pdf`;
}
